version: '2'
networks:
  backend:

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: silex_db
    networks:
      backend:
        aliases:
          - dbserver
  php:
    image: php:7-fpm
    expose:
      - "9000"
    volumes:
      - ./:/var/www/silex
    networks:
      backend:
        aliases:
          - php
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./docker/nginx/silex.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    networks:
      backend:
