version: '2'
services:
  php:
    image: php:7-fpm
    expose:
      - "9000"
    volumes:
      - ./:/var/www/silex
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    links:
      - php
    volumes:
      - ./docker/nginx/silex.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
